### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Murmiks** [0x151/Atomic#103]
How to change proxy in this cheat? And yes, if this cheat is for 1.12.2?

**Comment by 0x150** [comment]
1. multiplayer screen, click "Proxies" top left, enter proxy server ip:port, set proxy server type and hit "Okay" and click "back" to return to the menu. to reset, click "reset", then "back"
2. this one is for 1.18.1

**Comment by Murmiks** [comment]
А как для 1.17.1?

**Comment by Murmiks** [comment]
И да почему сменив прокси, у меня не получаеться зайти на сервер?

**Comment by 0x150** [comment]
Я не говорю по русски прости

**Comment by 0x150** [comment]
> А как для 1.17.1?

Нет поддержки 1.17.1, но вы можете найти старую сборку здесь: https://github.com/0x151/Atomic/raw/c58cad3209ea17ebff915c32a31bca8aa21c081f/builds/atomic_b13.jar

**Comment by 0x150** [comment]
> И да почему сменив прокси, у меня не получаеться зайти на сервер?

Тогда прокси недействителен или больше не активен

**Comment by Murmiks** [comment]
OK, thanks
