### ISSUE TITLE
Suggestion: autoinsult

### ISSUE THREAD

**Issue by Talpae** [0x151/Atomic#105]
Spams insults from a user inputted list

**Comment by sarnthilIsHorny** [comment]
Very Good Suggestion indeed.

**Comment by AryonLegacy** [comment]
based

**Comment by Talpae** [comment]
0x add

**Comment by sarnthilIsHorny** [comment]
> 0x add
https://media.tenor.co/videos/9d956e331241e5b343c5a0ac06a057c3/mp4

**Comment by sarnthilIsHorny** [comment]
> 0x add

[https://media.tenor.co/videos/9d956e331241e5b343c5a0ac06a057c3/mp4](url)

**Comment by 0x150** [comment]
doing somewhere soon when i get back to atomic
