### ISSUE TITLE
AtomicConsole Crash

### ISSUE THREAD

**Issue by Merphyx** [0x151/Atomic#109]
When I try to minimize the game and at the same time when the Atomic Console is open, the game will crash.

![ConsoleError](https://user-images.githubusercontent.com/75223499/147844088-3375f1b6-af43-49c2-b47c-a20380fe40c7.png)

Tested on (Windows 11, MultiMC Minecraft 1.18.1)

**Comment by Talpae** [comment]
Yeah console size is based on the window size and when window size = 0 it tries to divide by zero or something idk

0x said he'd fix it in the next update so for now, just close console when you minimise
