### ISSUE TITLE
Failed to download! This is not good.

### ISSUE THREAD

**Issue by vahrervert** [0x151/Atomic#81]
yeah so it doesnt work it worked yesterday, and now it doesnt.
basically it loads the modules and then it gets to the downloading latest jar file thing yes

Checking for updates...
Getting current mod file
Deleted old file
Downloading latest client jar
Failed to download! This is not good.

**Comment by aaashleyyyy** [comment]
what

**Comment by vahrervert** [comment]
> what

it doesnt work... does it for you?

**Comment by aaashleyyyy** [comment]
it does, this just didnt make any sense, please elaborate

**Comment by vahrervert** [comment]
> it does, this just didnt make any sense, please elaborate

whats ur discord

**Comment by aaashleyyyy** [comment]
Ashley the 2nd#7767

**Comment by aaashleyyyy** [comment]
Ashley the 2nd#7797 , oops

**Comment by 0x150** [comment]
your version is actually ancient, download from builds folder
