### ISSUE TITLE
Oresim Nether Xray Issue

### ISSUE THREAD

**Issue by Myotic** [0x151/Atomic#85]
Mr.0x151 if your reading this kindly fix the module oresim which spasht work when used for ancient debris doesn't quite work.
Great wishes from me keep up ur work and have a good day :D
            -Myotic

**Comment by 19MisterX98** [comment]
ancient debris works. Config issue

**Comment by Sephirone** [comment]
i tried but it doesn't really work

**Comment by fartdev** [comment]
try fixing your config

**Comment by Sephirone** [comment]
I did everything to fix the config. I think the server use some kind of protection

**Comment by Myotic** [comment]
It's working now thnx

**Comment by Myotic** [comment]
Works now

**Comment by aaashleyyyy** [comment]
close this shit
