### ISSUE TITLE
Page not found shit

### ISSUE THREAD

**Issue by Archcapes** [0x151/Atomic#90]
Why does it say page not found its so fucked

**Comment by 0x150** [comment]
where

**Comment by unixquuw** [comment]
> where
![image](https://user-images.githubusercontent.com/79478046/141284138-9751d791-e9c9-47d0-9106-53825b9cb36c.png)
this link is outdated.

**Comment by unixquuw** [comment]
![image](https://user-images.githubusercontent.com/79478046/141284176-1118fffb-d99f-40d4-82e3-ee1979987f08.png)

**Comment by unixquuw** [comment]
nvm im retarded, look in builds folder
