### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by Jiyutam** [0x151/Atomic#97]
Make support for 1.17.1 C:

**Comment by 19MisterX98** [comment]
atomic supports 1.17.1 bruh

**Comment by aaashleyyyy** [comment]
your reinstated

**Comment by Jiyutam** [comment]
![image](https://user-images.githubusercontent.com/93816081/143778012-a71481e7-b4cf-41c9-836f-9f7641866a13.png)

**Comment by 0x150** [comment]
get fabric api above v0.40.1

https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3537000

**Comment by Jiyutam** [comment]
Thx ❤
