### ISSUE TITLE
Wont work in 1.17.1

### ISSUE THREAD

**Issue by Bautigarzabal** [0x151/Atomic#98]
Mods folder:
fabric-api-0.43.1+1.17.jar
atomic-private_b15.jar

Log:
[latest.log](https://github.com/0x151/Atomic/files/7635009/latest.log)
 
What can i do?
I already tried with java 16 and 17
Edit: tried with atlauncher and microsoft one too
Edit 2: when i try with java 16 this appears in fabric crash
[fabric.txt](https://github.com/0x151/Atomic/files/7635136/fabric.txt)

**Comment by 0x150** [comment]
this is an 1.18 client

we updated like yesterday and there’s already retards asking why it wont work

**Comment by Bautigarzabal** [comment]
btw, In the about and in the readme it says that it is 1.17, sorry
is there any jar for 1.17?

**Comment by fartdev** [comment]
here last 1.17 build 
https://github.com/0x151/Atomic/tree/c58cad3209ea17ebff915c32a31bca8aa21c081f/builds
